### ISSUE TITLE
How does versionize track the version?

### ISSUE THREAD

**Issue by xiphoid24** [versionize/versionize#91] opened 2023-02-02 13:50 UTC
I am just getting started with versionize and I am trying to integrate it in our CI. I was wondering how versionize determines the current version to know what version to bump to. At times it seems to be using the version in the .csproj while at other times it seems to use the tags. 

In our case we will be using the `--pre-release` flag for release candidates and then aggregate the changelog when we have a full release. What we do not need is a tag for every pre-release created. Just the main releases.

I was also getting different results when running versionize using the `--pre-release` flag when I ran a dry run , `-d`, and when I did not run a dry run. This also lead to some confusion as to how versionize determines the current version.

This is the output I got when I ran it with `-d`. Notice the version bumped from `9.0.1-rc.0` to `9.0.1-rc.1`.
```
√ bumping version from 9.0.1-rc.0 to 9.0.1-rc.1 in projects

---
<a name="9.0.1-rc.1"></a>
## 9.0.1-rc.1 (2023-1-31)

### Bug Fixes

* added patch 1
* patch 2
---

√ updated CHANGELOG.md
```

This is the output I got when I did not run it with `-d`. Notice it says the version changed from `9.0.1-rc.0` to `9.0.1-rc.0` which is not a change at all.

```
√ bumping version from 9.0.1-rc.0 to 9.0.1-rc.0 in projects
√ updated CHANGELOG.md
√ committed changes in projects and CHANGELOG.md
√ tagged release as 9.0.1-rc.0

i Run `git push --follow-tags origin master` to push all changes including tags
```

I _think_ this was caused because I chose not to add a tag when the pre-release `9.0.1-rc.0` was created but the dry run implies the version would be increases properly when I ran it for real.

Any help or insight on what is going on would be greatly appreciated. Please let me know if there is any more information you need.

**Comment by cabauman** [comment] 2023-02-12 03:56
I agree with you regarding the preference of not wanting tags for pre-releases. And I can confirm the logic does currently depend on version tags. So, I think it would be a good change to make.

I was able to reproduce the non-changed version bump (because of the version tag dependency) but was unable to reproduce the different results between dry-run and non dry-run.

**Comment by cabauman** [comment] 2023-03-01 11:34
@xiphoid24 do you keep the same "chore(release): [version]" commit message format for pre-releases?
When using project version rather than tag version for bump logic, we need a different method of finding the last release commit, which I'm thinking of doing by searching for the "chore(release):" message prefix. But of course, if the commit message format is customized, that won't work.

**Comment by cabauman** [comment] 2023-04-09 10:08
To explicitly answer the question in the title, Versionize uses git tags to determine the version by default. But that can now be overridden via the new `--proj-version-bump-logic` flag. I'll go ahead and close this issue, but if you're able to provide reproduction steps for that inconsistency issue you mentioned, feel free to create a new issue. Thank you!

**Closed by cabauman** 2023-04-09 10:08 UTC
