### ISSUE TITLE
Azure Release Pipeline

### ISSUE THREAD

**Issue by shabirjan** [versionize/versionize#3] opened 2019-07-04 15:34 UTC
Hi

Thanks for such awesome tool, But is it possible to use this in my Release pipeline as task?

**Comment by iangregsondev** [comment] 2019-10-08 12:39
I would also be interested in this, did you manage to find out ?

**Comment by nerdybynature** [comment] 2021-01-05 07:35
I made it work in a POC pipeline by having two tasks:

```yml
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update Versionize -g'

- task: PowerShell@2
  displayName: 'Versionize'
  inputs:
    targetType: 'inline'
      script: |
        versionize --skip-dirty --skip-commit
```

**Comment by volkanpaksoy** [comment] 2021-03-01 06:09
@nerdybynature Thanks for the snippet. I'm in a similar situation (just using AWS pipeline). Just wondering: Are you also pushing tags to master branch as shown in the documentation "git push --follow-tags origin master"

For me to achieve this, I would need to create a new SSH key every time the pipeline runs and I would have to delete the key from AWS after it's pushed the code. This sounds a bit excessive to me but I cannot figure out another way. If I don't push I cannot keep incrementing the version.

How did you handle this situation?

**Comment by nerdybynature** [comment] 2021-03-01 07:50
@volkanpaksoy 

Yes, I've managed to do it the following way.
_(I run a forked and modified version of the tool but that shouldn't be an issue.)_

```yml
steps:
- task: DotNetCoreCLI@2
  displayName: Install Versionize Tool
  inputs:
    command: custom
    custom: tool
    arguments: 'update -g Forked.Versionize --ignore-failed-sources --add-source { my nuget feed url }'

- script: |
    git config --global user.email "pipeline.bot@example.com"
    git config --global user.name "pipeline-bot"
    versionize-forked --skip-dirty
  displayName: "Run Versionize"
```

The important part is the `git config` commands just before running the tool.

Then at the end of our pipeline I run:

```yml
steps:
- task: PowerShell@2
  displayName: 'Git push changes and version tag'
  inputs:
    targetType: 'inline'
    script: |
      $pushUrl = "$(Build.Repository.Uri)".Substring("$(Build.Repository.Uri)".IndexOf("@dev.azure.com"))
      git push https://$(System.AccessToken)$pushUrl --follow-tags HEAD:master

```
End result:
![image](https://user-images.githubusercontent.com/1333979/109467097-f4603580-7a6a-11eb-8688-eef8ebbbc2e0.png)

**Comment by volkanpaksoy** [comment] 2021-03-01 07:59
@nerdybynature 

Thank you very much for sharing your solution. I'm going to investigate if AWS has something equivalent to System.AccessToken.

**Comment by kwinyyyc** [comment] 2021-05-11 07:24
I am trying to run `versionize` on Azure Devops too, it turns out failing with below error.
The remote url `.git` suffix is missing when running on Azure Devops while running `versionize` locally, it works fine, it detects the remote url syntax correctly.

Anyone encountered the same? 
![image](https://user-images.githubusercontent.com/8462684/117775039-adfa3480-b26c-11eb-8dea-c39f6683db64.png)

**Comment by kwinyyyc** [comment] 2021-05-12 02:25
Yes, I created a new pipeline and choose GitHub on the "Where is your code?" step.

I also just tried creating a public repo with minimal code on Github, it throw the same error.

And then I tried to move the repo to Azure Devops Repo, it works fine. So seems like it is only happening on Github repo

**Comment by nerdybynature** [comment] 2021-05-13 16:37
I finally got approval to run pipelines and was able to reproduce your issue.

One workaround that I found was to change the git remote url before running `versionize`, e.g.:
`git remote set-url origin "{your-url}.git`

I noticed when pushing back to GitHub from the pipeline that I needed to add a GitHub Personal Access Token for it to work.

**Comment by kwinyyyc** [comment] 2021-05-14 10:25
@nerdybynature thanks a lot for helping.

Though I face another issue, when running versionize on Azure Devops, the version does not update

tried `feat:` `feat(core):` `fix:` `fix(core)` but the version remain 1.0.0

if running locally, the version can be updated.

**Comment by nerdybynature** [comment] 2021-05-14 11:07
Do you always get the same result?
What was the version set in your `.csproj` file? What is the version now?
Did you have a proper versioning tag in your repo before running versionize? E.g. `v0.4.2`

**Comment by kwinyyyc** [comment] 2021-05-14 11:14
Yes, always get the same result
The version in `.csproj` is 1.0.0
I added the version before running versionize

**Comment by nerdybynature** [comment] 2021-05-14 11:16
Are you running `git push --follow-tags` after versionize?

**Comment by kwinyyyc** [comment] 2021-05-14 11:27
Yes I can actually share my task here

```
 - task: CmdLine@2
      displayName: Versionize
      inputs:
        script: |
          git checkout master
          dotnet tool install --global Versionize
          git config --global user.email "devops@ops.dev"
          git config --global user.name "Azure DevOps"
          git remote set-url origin "https://github.com/$(OrgName)/$(RepoName).git"
          versionize --skip-dirty
          git commit --amend -m "chore(release): [skip ci]  New version release"
          git push --follow-tags https://$(GH_TOKEN)@github.com/$(OrgName)/$(RepoName).git master
```

I have to checkout to master as azure devops is fetching a detached branch based on the last commit.
then I have to amend the commit message to put the [skip ci] text in it otherwise it will trigger another build when verisonize push the changes, so it would dead-looped

But I believe all these dont affect because I tried quite a lot of combination, I did put the `versionize --skip-dirty` at the very beginning and it would return
```
Discovered 1 versionable projects
  * /home/vsts/work/1/s/xxxxxxxxx/xxxxxxx.csproj
√ bumping version from 1.0.0 to 1.0.0 in projects
√ updated CHANGELOG.md
√ committed changes in projects and CHANGELOG.md
√ tagged release as 1.0.0
```

**Comment by kwinyyyc** [comment] 2021-05-14 11:38
Share my working Azure Devops task here.

```
 - task: CmdLine@2
      displayName: Versionize
      inputs:
        script: |
          git checkout master
          dotnet tool install --global Versionize
          git config --global user.email "$(Email)"
          git config --global user.name "$(Name)"
          git remote set-url origin "https://github.com/$(OrgName)/$(RepoName).git"
          versionize --skip-dirty
          git commit --amend -m "chore(release): [skip ci] New version release"
          git push --follow-tags https://$(GH_TOKEN)@github.com/$(OrgName)/$(RepoName).git master
```

**Comment by nerdybynature** [comment] 2021-05-14 11:40
> @nerdybynature
> 
> My bad, I just notice the [other issue related to version not updated](https://github.com/saintedlama/versionize/issues/1)
> 
> There need to be at least one tag already push as a base tag for it to work,
> 
> Problem solved, thanks!

Glad it got sorted out!

**Comment by cabauman** [comment] 2022-02-11 13:22
I'll go ahead and close this since the original question seems to have been answered (great examples).

**Closed by cabauman** 2022-02-11 13:22 UTC
Labels: question
