### ISSUE TITLE
Directory.Build.targets not supported

### ISSUE THREAD

**Issue by WeihanLi** [versionize/versionize#95] opened 2023-04-08 11:45 UTC
I had defined the `Version` prop in the `Directory.Build.targets` file in the project root folder, but it seemed it's not found

``` xml
<Project>
  <PropertyGroup>
    <Version Condition="'$(VersionSuffix)'==''">$(VersionPrefix)</Version>
    <Version Condition="'$(VersionSuffix)'!=''">$(VersionPrefix)-$(VersionSuffix)</Version>
  </PropertyGroup>
</Project>
```

https://github.com/WeihanLi/dotnet-exec/blob/4a918d632944c4093fc688e26ad802497c78e6ee/Directory.Build.targets

![image](https://user-images.githubusercontent.com/7604648/230719395-10597d5b-769c-4723-8b0f-79bd4ba749bb.png)

**Comment by cabauman** [comment] 2023-04-09 09:59
Yeah, supporting `Directory.Build.props`/`Directory.Build.targets` would be a nice feature. Not sure when one of us will get to it, but we'll keep an eye on this issue. Thank you.

**Comment by WeihanLi** [comment] 2023-04-09 13:46
It's simple to get the XML node inner text, while sometimes we may want to reference other variables, currently, we get the inner text only.

**Comment by cabauman** [comment] 2023-04-15 23:18
We'd be happy to add the targets file as a supported extension. But in your example snippet it still wouldn't work because Versionize, by design, only works with explicit version numbers (e.g. 1.2.3); not evaluated ones e.g. `$(VersionPrefix)`. This is because Versionize is responsible for writing the updated version back to the file where it read from.

**Comment by cabauman** [comment] 2024-06-15 07:43
Closing this because of my previous comment.

**Closed by cabauman** 2024-06-15 07:43 UTC
Labels: enhancement
